export interface LayoutItem {
  id: string;
  title: string;
}

export const layouts: LayoutItem[] = [
  { id: "cube", title: "הקוביה" },
  { id: "diagonal", title: "האלכסון" },
  { id: "ball", title: "הכדור" },
  { id: "frame", title: "המסגרת" },
  { id: "grid", title: "הגריד" },
  { id: "thirds", title: "השלישיות" },
  { id: "wave", title: "הגל" },
  { id: "corner", title: "הפינה" },
  { id: "layers", title: "השכבות" },
  { id: "zigzag", title: "הזיגזג" },
  { id: "window", title: "החלון" },
  { id: "gradient", title: "הגרדיאנט" },
  { id: "mosaic", title: "הפסיפס" },
  { id: "horizon", title: "האופק" },
  { id: "arch", title: "הקשת" },
  { id: "diamond", title: "היהלום" },
  { id: "spiral", title: "הספירלה" },
  { id: "ribbon", title: "הסרט" },
  { id: "pillars", title: "העמודים" },
  { id: "steps", title: "המדרגות" },
  { id: "eclipse", title: "הליקוי" },
  { id: "cross", title: "הצלב" },
  { id: "pyramid", title: "הפירמידה" },
  { id: "split", title: "הפיצול" },
  { id: "tiles", title: "האריחים" },
  { id: "curtain", title: "הווילון" },
  { id: "bridge", title: "הגשר" },
  { id: "nest", title: "הקן" },
  { id: "peak", title: "הפסגה" },
  { id: "orbit", title: "המסלול" },
  { id: "hexagon", title: "המשושה" },
  { id: "cinema", title: "הקולנוע" },
  { id: "origami", title: "האוריגמי" },
  { id: "float", title: "הריחוף" },
  { id: "slices", title: "הפרוסות" },
  { id: "focus", title: "המיקוד" },
  { id: "spectrum", title: "הספקטרום" },
  { id: "portal", title: "השער" },
  { id: "symmetry", title: "הסימטריה" },
  { id: "matrix", title: "המטריצה" },
];
